### ISSUE TITLE
Add support for Typescript 

### ISSUE THREAD

**Issue by rickyhaswifi** [codesweetly/react-youtube-playlist#1]
<img width="562" alt="image" src="https://github.com/codesweetly/react-youtube-playlist/assets/37841371/58f67d4d-2215-411d-81f5-901fd6989b68">

 Try `npm i --save-dev @types/codesweetly__react-youtube-playlist` if it exists or add a new declaration (.d.ts) file containing `declare module '@codesweetly/react-youtube-playlist';`ts(7016)

**Comment by aburnazy** [comment]
please add support for typescript

**Comment by oluwatobiss** [comment]
Thanks for raising this issue. A TypeScript version will be released soon...It will likely be in the next release.

**Comment by oluwatobiss** [comment]
The new version is out! 🎉 It's written in TypeScript, so I consider this issue closed.
