### ISSUE TITLE
Remove require() of CSS and move to a separate import into code

### ISSUE THREAD

**Issue by rickyhaswifi** [codesweetly/react-youtube-playlist#2]
<img width="1334" alt="image" src="https://github.com/codesweetly/react-youtube-playlist/assets/37841371/3e57f7a0-5772-4961-b09a-62de3d9b93b2">

Moving the CSS into a separate import would allow it to load properly on all versions of React. 

Using REMIX - https://remix.run/

**Comment by oluwatobiss** [comment]
Hi Ricardo. Thanks for raising this issue. The plugin wasn't tested with Remix, but I would love to make it work.

Please clarify what you mean by "Moving the CSS into a separate import."

**Comment by oluwatobiss** [comment]
The package now works with Remix!🎉

## Note

Add `"@codesweetly/react-youtube-playlist"` to your `remix.config.js` file:

```diff
/** @type {import('@remix-run/dev').AppConfig} */
module.exports = {
  ignoredRouteFiles: ["**/.*"],
+ serverDependenciesToBundle: ["@codesweetly/react-youtube-playlist"],
  serverModuleFormat: "cjs",
  future: {
    v2_dev: true,
    v2_errorBoundary: true,
    v2_headers: true,
    v2_meta: true,
    v2_normalizeFormMethod: true,
    v2_routeConvention: true,
  },
};
```

By so doing, Remix will transpile and include the package in the server bundle.

You can read more about the configuration option in the [official doc](https://remix.run/docs/en/1.19.0/file-conventions/remix-config#serverdependenciestobundle) or @dan-cooke's [issue comment](https://github.com/remix-run/remix/issues/4234#issuecomment-1317549172).
